/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsGuidesRoutingRouteImport } from './routes/docs/guides/routing'
import { Route as DocsGuidesStructureRouteImport } from './routes/docs/guides/structure'
import { Route as DocsGuidesStylingRouteImport } from './routes/docs/guides/styling'
import { Route as DocsReferenceApiRouteImport } from './routes/docs/reference/api'
import { Route as DocsReferenceCliRouteImport } from './routes/docs/reference/cli'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesRoutingRoute = DocsGuidesRoutingRouteImport.update({
  id: '/guides/routing',
  path: '/guides/routing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesStructureRoute = DocsGuidesStructureRouteImport.update({
  id: '/guides/structure',
  path: '/guides/structure',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesStylingRoute = DocsGuidesStylingRouteImport.update({
  id: '/guides/styling',
  path: '/guides/styling',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferenceApiRoute = DocsReferenceApiRouteImport.update({
  id: '/reference/api',
  path: '/reference/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferenceCliRoute = DocsReferenceCliRouteImport.update({
  id: '/reference/cli',
  path: '/reference/cli',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/guides/routing': typeof DocsGuidesRoutingRoute
  '/docs/guides/structure': typeof DocsGuidesStructureRoute
  '/docs/guides/styling': typeof DocsGuidesStylingRoute
  '/docs/reference/api': typeof DocsReferenceApiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs': typeof DocsIndexRoute
  '/docs/guides/routing': typeof DocsGuidesRoutingRoute
  '/docs/guides/structure': typeof DocsGuidesStructureRoute
  '/docs/guides/styling': typeof DocsGuidesStylingRoute
  '/docs/reference/api': typeof DocsReferenceApiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/guides/routing': typeof DocsGuidesRoutingRoute
  '/docs/guides/structure': typeof DocsGuidesStructureRoute
  '/docs/guides/styling': typeof DocsGuidesStylingRoute
  '/docs/reference/api': typeof DocsReferenceApiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/'
    | '/docs/guides/routing'
    | '/docs/guides/structure'
    | '/docs/guides/styling'
    | '/docs/reference/api'
    | '/docs/reference/cli'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs'
    | '/docs/guides/routing'
    | '/docs/guides/structure'
    | '/docs/guides/styling'
    | '/docs/reference/api'
    | '/docs/reference/cli'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/installation'
    | '/docs/'
    | '/docs/guides/routing'
    | '/docs/guides/structure'
    | '/docs/guides/styling'
    | '/docs/reference/api'
    | '/docs/reference/cli'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/routing': {
      id: '/docs/guides/routing'
      path: '/guides/routing'
      fullPath: '/docs/guides/routing'
      preLoaderRoute: typeof DocsGuidesRoutingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/structure': {
      id: '/docs/guides/structure'
      path: '/guides/structure'
      fullPath: '/docs/guides/structure'
      preLoaderRoute: typeof DocsGuidesStructureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/styling': {
      id: '/docs/guides/styling'
      path: '/guides/styling'
      fullPath: '/docs/guides/styling'
      preLoaderRoute: typeof DocsGuidesStylingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reference/api': {
      id: '/docs/reference/api'
      path: '/reference/api'
      fullPath: '/docs/reference/api'
      preLoaderRoute: typeof DocsReferenceApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reference/cli': {
      id: '/docs/reference/cli'
      path: '/reference/cli'
      fullPath: '/docs/reference/cli'
      preLoaderRoute: typeof DocsReferenceCliRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGuidesRoutingRoute: typeof DocsGuidesRoutingRoute
  DocsGuidesStructureRoute: typeof DocsGuidesStructureRoute
  DocsGuidesStylingRoute: typeof DocsGuidesStylingRoute
  DocsReferenceApiRoute: typeof DocsReferenceApiRoute
  DocsReferenceCliRoute: typeof DocsReferenceCliRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsGuidesRoutingRoute: DocsGuidesRoutingRoute,
  DocsGuidesStructureRoute: DocsGuidesStructureRoute,
  DocsGuidesStylingRoute: DocsGuidesStylingRoute,
  DocsReferenceApiRoute: DocsReferenceApiRoute,
  DocsReferenceCliRoute: DocsReferenceCliRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
